SELECT * FROM CLIENTE WHERE CIUDAD = 'MADRID';
SELECT * FROM CLIENTE WHERE CIUDAD <> 'MADRID';
SELECT * FROM CLIENTE WHERE NOMBRE Like "R%" or NOMBRE Like "C%";
SELECT * FROM CLIENTE WHERE NOMBRE LIKE 'P%';
SELECT * FROM PRODUCTO WHERE CODIGO = 'BAB5';
SELECT CODIGO, DESCRIPCION, STOCK, (MINIMO - STOCK) AS UNIDADES_A_REPONER, 
       (MINIMO - STOCK) * PRECIO AS DINERO 
FROM PRODUCTO 
WHERE STOCK < MINIMO;
SELECT DETALLE.*, PRODUCTO.DESCRIPCION, (DETALLE.UNIDADES * DETALLE.PRECIO) AS PRECIO_VENTA 
FROM DETALLE 
JOIN PRODUCTO ON DETALLE.CODIGO = PRODUCTO.CODIGO;
SELECT DETALLE.*, PRODUCTO.DESCRIPCION, (DETALLE.UNIDADES * DETALLE.PRECIO) AS PRECIO_VENTA 
FROM DETALLE 
JOIN PRODUCTO ON DETALLE.CODIGO = PRODUCTO.CODIGO 
WHERE DETALLE.NUMERO = 5000;
SELECT DETALLE.*, PRODUCTO.DESCRIPCION, (DETALLE.UNIDADES * DETALLE.PRECIO) AS PRECIO_VENTA 
FROM DETALLE 
JOIN PRODUCTO ON DETALLE.CODIGO = PRODUCTO.CODIGO 
WHERE DETALLE.CODIGO = 'BAB5';
SELECT FACTURA.*, CLIENTE.NOMBRE, CLIENTE.TLF 
FROM FACTURA 
JOIN CLIENTE ON FACTURA.NIF = CLIENTE.NIF;

SELECT FACTURA.*, CLIENTE.NOMBRE, CLIENTE.TLF, 
       SUM(DETALLE.UNIDADES * DETALLE.PRECIO) AS IMPORTE_TOTAL 
FROM FACTURA 
JOIN CLIENTE ON FACTURA.NIF = CLIENTE.NIF 
JOIN DETALLE ON FACTURA.NUMERO = DETALLE.NUMERO 
GROUP BY FACTURA.NUMERO;

SELECT FACTURA.*, CLIENTE.NOMBRE, CLIENTE.TLF, 
       SUM(DETALLE.UNIDADES * DETALLE.PRECIO) AS IMPORTE_TOTAL 
FROM FACTURA 
JOIN CLIENTE ON FACTURA.NIF = CLIENTE.NIF 
JOIN DETALLE ON FACTURA.NUMERO = DETALLE.NUMERO 
WHERE CLIENTE.NOMBRE = 'ROSA PEREZ DELGADO'
GROUP BY FACTURA.NUMERO;

SELECT FACTURA.*, CLIENTE.NOMBRE, CLIENTE.TLF, 
       SUM(DETALLE.UNIDADES * DETALLE.PRECIO) AS IMPORTE_TOTAL 
FROM FACTURA 
JOIN CLIENTE ON FACTURA.NIF = CLIENTE.NIF 
JOIN DETALLE ON FACTURA.NUMERO = DETALLE.NUMERO 
WHERE FACTURA.PAGADO = FALSE
GROUP BY FACTURA.NUMERO;

SELECT FACTURA.*, CLIENTE.NOMBRE, CLIENTE.TLF,
       SUM(DETALLE.UNIDADES * DETALLE.PRECIO) AS IMPORTE
FROM FACTURA
INNER JOIN CLIENTE ON FACTURA.NIF = CLIENTE.NIF
INNER JOIN DETALLE ON FACTURA.NUMERO = DETALLE.NUMERO
WHERE FACTURA.FECHA between "2021-06-18" and "2021-07-20"
GROUP BY FACTURA.NUMERO;

SELECT FACTURA.*, CLIENTE.NOMBRE, CLIENTE.TLF, 
       SUM(DETALLE.UNIDADES * DETALLE.PRECIO) AS IMPORTE_TOTAL 
FROM FACTURA 
JOIN CLIENTE ON FACTURA.NIF = CLIENTE.NIF 
JOIN DETALLE ON FACTURA.NUMERO = DETALLE.NUMERO 
GROUP BY FACTURA.NUMERO 
HAVING IMPORTE_TOTAL BETWEEN 40 AND 50;

SELECT SUM(DETALLE.UNIDADES * DETALLE.PRECIO) AS IMPORTE_TOTAL_PAGADO 
FROM FACTURA 
JOIN DETALLE ON FACTURA.NUMERO = DETALLE.NUMERO 
WHERE FACTURA.PAGADO = TRUE;

SELECT SUM(DETALLE.UNIDADES * DETALLE.PRECIO) AS IMPORTE_TOTAL_ROSA 
FROM FACTURA 
JOIN CLIENTE ON FACTURA.NIF = CLIENTE.NIF 
JOIN DETALLE ON FACTURA.NUMERO = DETALLE.NUMERO 
WHERE CLIENTE.NOMBRE = 'ROSA PEREZ DELGADO';

SELECT PRODUCTO.CODIGO, PRODUCTO.DESCRIPCION, 
       SUM(DETALLE.UNIDADES) AS UNIDADES_TOTALES, 
       SUM(DETALLE.UNIDADES * DETALLE.PRECIO) AS IMPORTE_RECAUDADO 
FROM PRODUCTO 
JOIN DETALLE ON PRODUCTO.CODIGO = DETALLE.CODIGO 
GROUP BY PRODUCTO.CODIGO;

SELECT CLIENTE.NOMBRE, COUNT(FACTURA.NUMERO) AS TOTAL_FACTURAS 
FROM CLIENTE 
JOIN FACTURA ON CLIENTE.NIF = FACTURA.NIF 
GROUP BY CLIENTE.NOMBRE;

SELECT SUM((MINIMO - STOCK) * PRECIO) AS TOTAL_REPOSICION 
FROM PRODUCTO 
WHERE STOCK < MINIMO;

UPDATE PRODUCTO 
SET PRECIO = PRECIO * 1.03 
WHERE CODIGO = 'BAF4';

INSERT INTO FACTURA (NUMERO, FECHA, PAGADO, NIF) 
VALUES (5010, CURDATE(), FALSE, '11111111A');

DELETE FROM FACTURA 
WHERE NUMERO = 5010;


SELECT PRODUCTO.CODIGO, PRODUCTO.DESCRIPCION, 
       SUM(DETALLE.UNIDADES) AS UNIDADES_VENDIDAS 
FROM PRODUCTO 
JOIN DETALLE ON PRODUCTO.CODIGO = DETALLE.CODIGO 
GROUP BY PRODUCTO.CODIGO;

